// puzzles.js — generated by scripts/puz-to-js.js — do not edit by hand
// Source: apps/games/puzzles/source/  Manifest: apps/games/puzzles/manifest.json

const PUZZLES = [
  {
    title: "Daily 49",
    grid:  "##ODE#PRIXPIANOAUTO#SSE##",
    clues: {
      across: {
        1: "Poem of praise",
        4: "Grand ___ (Mario Kart game mode)",
        5: "Grand ___ (instrument)",
        6: "Grand theft ___",
        7: "Opposite of NNW"
      },
      down:   {
        1: "Give a speech",
        2: "T-Rex, e.g., for short",
        3: "Skeleton prefix",
        4: "Apt name of 12 popes",
        5: "Faux ___"
      }
    }
  }
];
