server {
    listen 80;
    server_name homehub.local;

    location / {
        root /var/www/homehub/apps/dashboard;
        index home-hub.html;
        try_files $uri $uri/ =404;
    }

    location /games {
        alias /var/www/homehub/apps/games;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
