substitutions:
  node_name: office-sensor
  friendly_name: Office Sensor
  room_name: Office

esphome:
  name: ${node_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

sensor:
  - platform: dht
    pin: GPIO16
    model: DHT22
    temperature:
      name: "${room_name} Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * 9.0/5.0 + 32.0;
    humidity:
      name: "${room_name} Humidity"
    update_interval: 60s
