substitutions:
  node_name: living-room-sensor
  friendly_name: Living Room Sensor
  room_name: Living Room

esphome:
  name: ${node_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

sensor:
  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      name: "${room_name} Temperature"
    humidity:
      name: "${room_name} Humidity"
    update_interval: 60s
